name: ryoTenKa
version: '1.0-SNAPSHOT'
main: org.useop0311.ryoTenKa.RyoTenKa
api-version: '1.21'
description: Add Expansion Game
commands:
  start:
    description: '게임 시작'
    usage: /start
  escape:
    description: '사망 횟수 5회 차감'
    usage: /escape
  doklib:
    description: '독립하기'
    usage: /doklib
